/* 액션 타입 정의 */
// 액션 타입은 주로 대문자로 작성합니다.
const constants = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  UPDATE_USER_STAMP: "UPDATE_USER_STAMP",
  UPDATE_USER_REGION: "UPDATE_USER_REGION",
  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
  UPDATE_USER_PHONE_NUMBER: "UPDATE_USER_PHONE_NUMBER",
  UPDATE_USER_FOLLOWINGS: "UPDATE_USER_FOLLOWINGS",
};
export default constants;
